config/routes.rb
Holla2::Application.routes.draw do

  
  resources :messages
  resources :channels
  resources :assets  
  resources :app
  
  match "/assets/*:id" => "assets#show"
  
  match "/auth/twitter/callback" => "authorize#create"
  match "/auth/failure" => "authorize#failure"
  match "/logout" => "authorize#destroy", :as => :logout
  match "/authorize" => redirect("/auth/twitter")
  
  root :to => "app#index"
end

app/models/asset.rb
class Asset < CarrierWave::Uploader::Base
  storage :file
  
  class << self
    def find(id)
      self.new.tap do |rec|
        rec.retrieve_from_store!(id)
      end
    end
    
    def create(file)
      file = CarrierWave::SanitizedFile.new(file)
      self.new.tap do |rec|
        rec.store!({
          :tempfile => file,
          :filename => generate_name(file)
        })
      end
    end
    
    protected
      def generate_name(file)
        ActiveSupport::SecureRandom.hex(13)
      end
  end
    
  def store_dir
    File.join("system", "uploads")
  end
  
  def id
    filename
  end
  alias_method :to_s, :id

  def persisted?
    true
  end  
  
  extend ActiveModel::Naming
  include ActiveModel::Conversion
end

app/models/channel.rb
class Channel < ActiveRecord::Base
  has_many :messages, :dependent => :destroy
  
  # include ActiveRecord::GUID
  
  attr_accessible :id, :name
end

app/models/message.rb
class Message < ActiveRecord::Base
  belongs_to :channel
  
  validates_presence_of :body, :channel_id
  
  attr_accessible :id, :body, :name, :channel_id
  
  # include ActiveRecord::GUID
end

app/controllers/app_controller.rb
class AppController < ApplicationController
  before_filter :require_user
  layout false
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  
  protected
    def current_user
      cookies.signed[:handle]
    end
    
    def require_user
      unless current_user        
        respond_to do |format|
          format.html  { 
            flash[:error] = "You must be logged in to access this page"
            redirect_to "/authorize"          
          }
          format.all { 
            head(:unauthorized)
          }
        end
        return false
      end
    end
    
    helper_method :current_user
end

app/controllers/assets_controller.rb
class AssetsController < ApplicationController
  def show
    @asset = Asset.find(params[:id])
    send_file @asset.path
  end
  
  def create
    @asset = Asset.create(params[:file])
    render :json => {:url => asset_url(@asset)}
  end  
end

app/controllers/authorize_controller.rb
class AuthorizeController < ApplicationController
  def create
    cookies.permanent.signed[:handle] = request.env["omniauth.auth"]["user_info"]["nickname"]
    redirect_to "/"
  end
  
  def failure
    raise "OAuth failure - #{params[:message]}"
  end
  
  def destroy
    cookies.delete(:handle)
  end
end

app/controllers/channels_controller.rb
class ChannelsController < ApplicationController
  before_filter :require_user
  before_filter :find_channel, :only => [:update, :destroy]
  
  def index
    @channels = Channel.all
    render :json => @channels
  end
  
  def create
    Channel.create!(params)
    head :ok
  end
  
  def update
    @channel.update_attributes!(params)
    head :ok
  end
  
  def destroy
    @channel.destroy
    head :ok
  end
  
  private
    def find_channel
      @channel = Channel.find(params[:id])
    end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_filter :require_user
  
  def index
    @messages = Message.all
    render :json => @messages
  end
  
  def create
    message = Message.new(params)
    message.name = current_user
    message.save!
    head :ok
  end
  
  def update
    message = Message.find(params[:id])
    message.name = current_user
    message.update_attributes!(params)
    head :ok
  end
end

app/helpers/app_helper.rb
module AppHelper
  def script_template(name, id = nil)
    id ||= name
    id += "_template"
    id = id.camelize(:lower)
    content_tag(:script, :type => "text/template", :id => id) do
      render :partial => name
    end
  end
  
  def meta_tag(name, value)
    %(<meta name="#{name}" content="#{Rack::Utils.escape_html(value)}"/>).html_safe    
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/assets_helper.rb
module AssetsHelper
end

app/helpers/authorize_helper.rb
module AuthorizeHelper
end

app/helpers/channels_helper.rb
module ChannelsHelper
end

app/views/app/_edit_channel.html.erb
<div class="view" title="Double click to edit...">
  <span>${name}</span> <a class="destroy"></a>
</div>

<div class="edit">
  <input type="text" value="${name}">
</div>

app/views/app/_message.html.erb
<li class="item">
  <span class="name">${name || "(unknown)"}</span>
  <span class="body">${body}</span>
</li>

app/views/app/_search.html.erb
<li class="item">
  <span class="name">${record.name || "(unknown)"}</span>
  <span class="body">${record.body}</span>
</li>

app/views/app/index.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Holla</title>
  <%= stylesheet_link_tag "application" %>
  <%= csrf_meta_tag %>
  <%= meta_tag "handle", current_user %>
  <%= javascript_include_tag :juggernaut, "application" %>
</head>
<body>
  <header id="title">
    <h1>Holla</h1>    
  </header>
  
  <div id="wrapper">
    <div id="sidebar">
      <h3>Channels</h3>
      <ul id="channels">
      </ul>
    
      <h3>Options</h3>
      <ul id="options">
        <li data-name="settings">Settings</li>
      </ul>
      
      <h3>Search</h3>
      <input type="search" results="0" incremental="true" placeholder="Search">
    </div>
    
    <div class="vdivide"></div>
  
    <div id="content">
      <div id="messages">
        <ul class="items">
        </ul>
        
        <div class="new">
          <textarea></textarea>
          <button>Send</button>
        </div>
      </div>
      
      <div id="searches">
        <h2>Search results: <span class="query"></span></h2>
        <ul class="items"></ul>
      </div>
      
      <div id="settings">
        <h2>Channels</h2>
        <ul class="channels">    
        </ul>
        
        <h2>Create Channel</h2>
        <div class="createChannel">
          <form>
            <input type="text" placeholder="Channel name">
            <button class="pill">New Channel</button>
          </form>
        </div>

        <h2>Profile</h2>

        <div><%= link_to "Logout", logout_path %></div>
      </div>
    </div>
  </div>
  
  <%= script_template "message" %>
  <%= script_template "channels" %>
  <%= script_template "edit_channel" %>
  <%= script_template "search" %>
</body>
</html>

app/views/authorize/destroy.html.erb
<h1>Successfully logged out</h1>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Holla2</title>
  <%= stylesheet_link_tag :all %>
  <%= javascript_include_tag :defaults %>
  <%= csrf_meta_tag %>
</head>
<body>

<%= yield %>

</body>
</html>